services:
  pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=customer-chat
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
      - "db:/var/lib/postgresql/data"

volumes:
  db:
